covid19fypproj/covid19app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .data_tables import ExpertListJson
from django.conf.urls.static import static
from django.conf import settings

app_name = 'covid19app'


urlpatterns = [
    path('', views.home, name="home"),
    path('logout', views.logout_view, name = 'logout'),
    path('login', views.login_page, name="login"),
    path('medical', views.medical, name="medical"),
    path('medical/<int:pk>', views.medical_find ,name='medical_find'),
    path('medical/new', views.addRecord, name="addRecord"),
    path('medical/<int:pk>/edit', views.edit_record, name = 'editRecord'),
    path('medical/<int:pk>/view', views.view_record , name = 'viewRecord'),
    path('medical/<int:pk>/delete', views.delete_record, name = 'deleteRecord'),
    path('medical/<int:pk>/delete_record', views.view_deleted_record , name = 'view_deleted_record'),
    path('datatable/data' ,ExpertListJson.as_view() , name = 'expert_list_json'),
    path('it_expert', views.IT_expert, name="it_expert"),
    path('help', views.help_page, name='help_page'),
    path('new', views.test_celery_route , name = 'name_page'),
    path('new/<uuid:task_id>', views.test_view_celery_result, name = 'test_view_celery_result'),
    


    


]




urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid19fypproj/covid19fypproj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('covid19app.urls')),
    path('celery-progress/', include('celery_progress.urls')),
]


handler404 = "covid19app.views.page_not_found_view"

handler500 = "covid19app.views.handler500"

covid19fypproj/covid19app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User, expertdata
from django.forms import ClearableFileInput
import os
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.core.validators import MinValueValidator
from decimal import Decimal

# Create your forms here.

class LoginForm(forms.Form):
	username = forms.CharField(
		widget = forms.TextInput(
			attrs = {
				"class": "form-control"
			}
		)
	)

	password = forms.CharField(
		widget = forms.PasswordInput(
			attrs = {
				"class": "form-control"
			}
		)
	)
	class Meta:
		model = User
		fields = ("username", "password", 'Is_medical', 'Is_expert')


def validate_file_extension(value):
   
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.png', '.jpeg', '.jpg']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Must be image with .png, .jpeg, .jpg extension')


class ImageForm(forms.ModelForm):

	files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}),validators =[validate_file_extension])

	class Meta:
		model = expertdata
		fields = ['age' , 'continent' , 'gender' , 'files']






class PublicForm(forms.ModelForm):

	# file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	# img = forms.FileField(validators =[validate_file_extension])


	def clean_image_data(self):

		return self.cleaned_data.get('image')

	class Meta:
		model = expertdata
		#Age group
		fields = ['age', 'continent', 'gender' , 'image']
		# widgets = {
  #           'file': ClearableFileInput(attrs={'multiple': True})
  #       }

class ExpertForm(forms.Form):

	class Meta:
		fields = ['dataset_directory', 'Training_data_ratio', 'batch_size', 'Models_to_use',\
		'Learning_Rate', 'Activation' , 'Regularization' , 'Regularization_Rate'
		]
	


class Covid19Form(forms.Form):

	#do not allow them to let them choose

	LOW = 16
	NORMAL = 32
	TEN_PERCENT = 10
	TWENTY_PERCENT = 20
	THIRTY_PERCENT = 30
	BATCH_SIZE_CHOICES = (
    (LOW, '16'),
    (NORMAL, '32'),
    )

    

	# only 10% 20% or 30%
	TRAINING_RATIO_CHOICES = (
		(TEN_PERCENT, '10'),
		(TWENTY_PERCENT , '20'),
		(THIRTY_PERCENT, '30'),
		)
    #vgg16 , resnet50 , inception v3

	VGG16 = 'vgg16'
	VGG19 = 'vgg19'
	INCEPTIONV3 = 'inceptionv3'


	MODELS_TO_USE_CHOICES =(
		(VGG16 , 'VGG16'),
		(VGG19 , 'VGG19'),
		(INCEPTIONV3, 'InceptionV3'),
		)

    
	SOFTMAX = 'softmax'
	SIGMOID = 'sigmoid'
	RELU = 'relu'


	ACTIVATION_METHOD_CHOICES = (
		(SOFTMAX, 'softmax'),
		(SIGMOID, 'sigmoid'),
		(RELU, 'relu'),
		)



	# directory = forms.CharField(max_length=100) # maybe remove this 
	training_ratio = forms.TypedChoiceField(choices = TRAINING_RATIO_CHOICES, label='Training Ratio',initial=10,\
		help_text = 'Refers to the percentage to be allocated for test'
		)
	batch_size = forms.TypedChoiceField(choices=BATCH_SIZE_CHOICES,label='Batch Size',initial=16,\
		help_text = 'Refers to the number of training examples utilized in one iteration. Use either 16 or 32'
		)
	models_to_use = forms.TypedChoiceField(choices = MODELS_TO_USE_CHOICES , label='Models to Use', initial='vgg16',\
		help_text =mark_safe('One of the three models to use for deep learning. <a href="https://keras.io/api/applications/vgg/">Read more here</a>.')
		)
	learning_rate = forms.DecimalField(decimal_places=5 ,validators =[MinValueValidator(Decimal('0.00001'))], max_digits = 6,label='Learning Rate',\
		help_text = mark_safe('Set to allow models to learn x-ray images at a lower rate  <a href="/help">Read more here</a>.'),
		)
	activation_method = forms.TypedChoiceField(choices = ACTIVATION_METHOD_CHOICES, label = 'Activation Method' , \
		help_text='Refers to the activation method to train the models',required=False)
	
	

covid19fypproj/covid19app/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.urls import reverse , reverse_lazy
from django.http import HttpResponse
from django.contrib.auth  import  authenticate , login , logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm #add this
from .forms import LoginForm , ImageForm , PublicForm , Covid19Form, ExpertForm
from .models import expertdata ,Result
from .filters import ImageFilter
from .permissions import medical_required , expert_required , login_excluded , logout_excluded , admin_only
from django.contrib.auth.decorators import user_passes_test 
import logging
from django.http import HttpResponse
import matplotlib.pyplot as plt
import tensorflow as tf
from PIL import Image
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from .neural_network import hyperParameterTuning

from celery.result import AsyncResult
from keras.preprocessing import image
from .apps import Covid19AppConfig
from .task import go_to_sleep , add , get_all_data



@login_required(login_url='covid19app:login')
def test_celery_route(request):

    # sleep = go_to_sleep.delay(10)
    sleep = get_all_data.delay()
    

    return render(request, 'covid19app/new.html', {'task_id': sleep})


@login_required(login_url='covid19app:login')
def test_view_celery_result(request , task_id):

    status = AsyncResult(task_id)
    result = None

    if status.state == 'SUCCESS':
        result =status.result




    

    return render(request, 'covid19app/result.html', {'task_id': task_id, \
        'status' :status , 'result': result})




# model = tf.keras.models.load_model('static/models/vgg16_model.h5',\
#   custom_objects={'KerasLayer': hub.KerasLayer})


class_names = ['NEGATIVE','POSITIVE']

# Create your views here.


def load_and_prep_image(filename, img_shape=224):
  """
  Reads an image from filename, turns it into a tensor
  and reshapes it to (img_shape, img_shape, colour_channel).
  """
  # Decode the read file into a tensor & ensure 3 colour channels
  img = tf.io.read_file(filename)
 
  # (our model is trained on images with 3 colour channels and sometimes images have 4 colour channels)
  img = tf.image.decode_image(img, channels=3)

  # Resize the image (to the same size our model was trained on)
  img = tf.image.resize(img, size = [img_shape, img_shape])

  # Rescale the image (get all values between 0 and 1)
  img = img/255.
  return img




def home(request): # public user page
    form = PublicForm()
    pred = None
    value = None
    if request.method == 'POST':
        form = PublicForm(request.POST , request.FILES)
       
        if form.is_valid():
            print('chun was here!')
           
            new_file = form.save(commit=False)
            obj = expertdata(age = new_file.age, continent = new_file.continent , \
                    gender = new_file.gender , image = new_file.image, prediction = 25)
            obj.save() #save the instance
            messages.success(request, f'successfully uploaded files!')

            data = expertdata.objects.first()
            print(data.image)


            

            img = image.load_img(f'{data.image}',target_size=(224,224))
            img = np.asarray(img)
            img = np.expand_dims(img, axis=0)
            print(img.shape)

            vgg16 , vgg19 , inceptionv3 = 0 , 0 ,0 

            output = Covid19AppConfig.vgg16.predict(img)
            if output[0][0] > output[0][1]:
                print("POSITIVE")
                print(output[0][0])
                print(output[0][1])
                pred = 'Positive' 
                vgg16 = float(round(output[0][1], 2))

            else:
                print('NEGATIVE')
                print(output[0][0])
                print(output[0][1])
                pred = 'Negative'
                vgg16 = float(round(output[0][0], 2))

            output1 = Covid19AppConfig.vgg19.predict(img)
            if output1[0][0] > output1[0][1]:
                print("POSITIVE")
                print(output1[0][0])
                print(output1[0][1])
                pred = 'Positive' 
                vgg19 = float(round(output1[0][1], 2))
                value = vgg19

            else:
                print('NEGATIVE')
                print(output1[0][0])
                print(output1[0][1])
                pred = 'Negative'
                vgg19 = float(round(output1[0][0], 2))
                value = vgg19


            output2 = Covid19AppConfig.inceptionv3.predict(img)
            if output2[0][0] > output2[0][1]:
                print("POSITIVE")
                print(output2[0][0])
                print(output2[0][1])
                # pred = 'Positive' 
                inceptionv3 = float(round(output2[0][1], 2))

            else:
                print('NEGATIVE')
                print(output2[0][0])
                print(output2[0][1])
                # pred = 'Negative'
                inceptionv3 = float(round(output2[0][0] , 2))


            result = Result.objects.create(userid=data, inceptionv3_result=inceptionv3,\
                    vgg16_result=vgg16,\
                    vgg19_result=vgg19)
           

            data.prediction = float(value) * 100

            data.save()

            # pred = class_names[int(tf.round(prediction[0][0]))]
            # print(prediction[0][0])
                # return redirect(redirect('covid19app:home', kwargs = {'form': form}))
        # might be a problem when i refresh
        # its either i can redirect to request another page or something else
            return render(request , 'covid19app/home.html', {'form': form ,"obj" : obj , "pred" : pred })
   
    return render(request, "covid19app/home.html", {'form': form , "pred": pred })



@login_excluded('covid19app:home')
def login_page(request):


    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_Medical:
                login(request, user)
                messages.success(request, 'successfully logged in ')
                return redirect("covid19app:medical")
            elif user is not None and user.is_Expert:
                login(request, user)
                messages.success(request, 'successfully logged in ')
                return redirect("covid19app:it_expert")
            else:
                messages.error(request, 'Username or password is wrong, please try again.')
                return redirect('covid19app:login')
        else:
            messages.error(request, 'error, please check again.')
    return render(request, 'covid19app/login.html', {'form':form, 'msg':msg})

 



@logout_excluded('covid19app:home')
def logout_view(request):
    logout(request)
    messages.info(request, 'successfully logged out')
    return redirect('covid19app:home')


@medical_required
def medical(request):

    form2 = Covid19Form(request.POST or None)

    
    return render(request, 'covid19app/medical.html', {'data':expertdata.objects.all().reverse() , 'form2': form2})

def medical_find(request , pk):

    data = expertdata.objects.get(pk = pk)
    print(data)
    context = {
        'data' : data
    }

    return render(request , 'covid19app/medical_view.html', context)


# @login_required(login_url='login')


@expert_required
def IT_expert(request):

   
    form2 = Covid19Form(request.POST or None)


    data = expertdata.objects.all().reverse()

    if request.method =='POST' and form2.is_valid():
        training_ratio = form2.cleaned_data.get('training_ratio')
        learning_rate = form2.cleaned_data.get('learning_rate')
        print(training_ratio , learning_rate)

    return render(request, 'covid19app/it_expert.html' , {'form2': form2 , 'data': data})


def preprocess_image_from_infile_memory(img , shape=224):
    img = cv2.imdecode(np.frombuffer(img.read() , np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.resize(img , (224,224))
    img = np.asarray(img).astype(np.float32)
    img = img /255.
    
    print(img.shape)
    img = np.expand_dims(img , axis=0)
    img = np.reshape(img , [1,shape,shape,3])

    return img



@medical_required
def addRecord(request):
    '''
        here we add in more images 
        change / add in 1 more file to expertdata , filefield to accept mutiple images
        insert codes for machine learning
    '''
    form = ImageForm()
    
    #[{'name': }] 


    total = []
    if request.method == 'POST':
        form = ImageForm(request.POST , request.FILES)
        files = request.FILES.getlist('files')
        count = len(files)
        if form.is_valid():
            new_file = form.save(commit=False)
            print('chun was here!')
            count = 0



            for i in request.FILES.getlist('files'):
                # print(i.name)
                # img = preprocess_image_from_infile_memory(i.name)
                # prediction = Covid19AppConfig.vgg16.predict(img)

                # prediction = prediction[0][0] * 100
               
                obj = expertdata(age = new_file.age, continent = new_file.continent , \
                        gender = new_file.gender , image = i, prediction = 25)
                count+= 1
                obj.save() #save the instance


                 
            predict = expertdata.objects.all()[:count]
            for i in predict:
                d ={}
                prediction = load_and_prep_image(f'{i.image}', 224)
                prediction3 = Covid19AppConfig.vgg16.predict(tf.expand_dims(prediction,axis=0))

                prediction1 = Covid19AppConfig.inceptionv3.predict(tf.expand_dims(prediction,axis=0))

covid19fypproj/covid19app/templates/covid19app/_messages.html
 {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role ='alert'> 
                <a class="close" data-dismiss="alert">×</a>
                   <div class='text-center'>
                        {{ message|safe }}
                   </div>
            </div>
        {% endfor %}
    {% endif %}

covid19fypproj/covid19app/templates/covid19app/backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table, td, th, tr {
            border: 2px solid black;
        }
    </style>
</head>
<body>
    {% extends 'base.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label>Age</label>
          <input type="text" name="age" class="form-control" placeholder="Enter Age">
        </div>
        <div class="form-group">
          <label>Country</label>
          <input type="text" name="country" class="form-control" placeholder="Enter Country">
        </div>
        <div class="form-group">
            <label>Gender</label>
            <select name="gender" class="form-control">
              <option>Male</option>
              <option>Female</option>
            </select>
        </div>
        <div class="form-group">
        <label>X-ray image</label>
        <input type="file" name="filetype" class="form-control-file">
        </div>
        <br>
        <button type="submit" name="submitbtn" class="btn btn-primary">Submit</button>
      </form>
      {% endblock %}
</body>
</html>

covid19fypproj/covid19app/templates/covid19app/filter.html
 <div class ="container">
    <table class="table" id='myTable'>
  <thead class='thead-dark'>
    <tr>
      <th>ID</th>
      <th>day</th>
      <th>month</th>
      <th>year</th>
      <th >Age Group</th>
      <th >Continent</th>
      <th >Gender</th>
      <th >InceptionV3 Result</th>
      <th >VGG16 Result</th>
      <th >VGG19 Result</th>
       
       <th>Best Prediction</th>
       <th style= 'background-color: black;'></th>
       <th style= 'background-color: black;'></th>
    </tr>
  </thead>
  <tbody>
    {% for statistics in data %}
    <tr>
      <td >{{statistics.id}}</td>
      <td>{{statistics.day}}</td>
      <td>{{statistics.month}}</td>
      <td>{{statistics.year}}</td>
      <td>{{statistics.age}}</td>
      <td >{{statistics.continent}}</td>
      <td >{{statistics.gender}}</td>

      {% if statistics.result.inceptionv3_result > 0.4 %}
         <td>POSITIVE</td>
      {% else %}
          <td>NEGATIVE</td>
      {% endif %}

      {% if statistics.result.vgg16_result > 0.4 %}
         <td>POSITIVE</td>
      {% else %}
        <td>NEGATIVE</td>
      {% endif %}



      {% if statistics.result.vgg19_result > 0.4 %}

        <td>POSITIVE</td>
      {% else %}
          <td>NEGATIVE</td>
      {% endif %}

      
      
     <td>{{ statistics.result.prediction }}</td>

      <td>
        
        <a href = '{% url "covid19app:editRecord" statistics.id %}' class='btn btn-outline-primary'
        
        >Edit</a>
       
      </td>
       <td>
        
       
        <a href = "{% url 'covid19app:deleteRecord' statistics.id %}" class='btn btn-danger'
        
        >Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>


</table>





<script>
	$(document).ready( function () {

  // $('#myTable tfoot th').each( function () {
  //       var title = $(this).text();
  //       $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  //   } );
 

      var table = $('#myTable').DataTable({


      });
});



</script>

covid19fypproj/covid19app/templates/covid19app/footer.html
<footer class="sticky-footer bg-light text-center text-lg-start navbar-dark bg-light">
  <!-- Copyright -->
  <div class="text-center p-3">
    © 2022 Copyright:
    <a class="text-dark" href="https://desmondchin5383.wixsite.com/healthcheck">HealthCheck</a>
  </div>
  <!-- Copyright -->
</footer>

covid19fypproj/covid19app/templates/covid19app/home.html
{% extends 'base.html' %}


{% block content %}

{% include 'covid19app/_messages.html' %}

    <div>
        {% include 'covid19app/public.html' %}
    </div>

   

{% endblock %}

covid19fypproj/covid19app/templates/covid19app/medical.html
  {% extends 'base.html' %}
  {% load crispy_forms_tags %}
  {% block content %}

{% include 'covid19app/_messages.html' %}


     
      {% if user.is_Medical %}
        <div class='d-flex justify-content-end mb-4'>
            <a href='{% url "covid19app:addRecord" %}' class='btn btn-primary' type="button">Add Record <i class="fa-solid fa-plus"></i></a>
       </div>


      {% endif %}

      <div class="container">
        <div class="row">
          <div class="col-sm">
            <div class="col">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-center">
                    <h6 class="m-0 font-weight-bold text-primary">Total Covid-19 Cases</h6>
                    <div class="dropdown no-arrow">
                        
                        
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                         <div id= "chart2" class ='mb-4'></div>
                    </div>
                    <div class="mt-4 text-center small">
                      <!--   <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Direct
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Social
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Referral
                        </span> -->
                    </div>
                </div>
            </div>
        </div>
          </div>
          <div class="col-sm">
            
            <div class="col">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-center">
                    <h6 class="m-0 font-weight-bold text-primary">Total Records by Continent</h6>
                    <div class="dropdown no-arrow">
                        
                        
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                         <div id= "container" class ='mb-4'></div>
                    </div>
                    <div class="mt-4 text-center small">
                        <!-- <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Direct
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Social
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Referral
                        </span> -->
                    </div>
                </div>
            </div>
        </div>
    </div>

          </div>
          <!-- third graph -->
          <div class="col-sm">
            
          </div>
        </div>
      </div>

      
       
        


  <div class ="container">
    <table class="table" id='myTable'>
  <thead class='thead-dark'>
    <tr>
      <th>ID</th>
      <th>day</th>
      <th>month</th>
      <th>year</th>
      <th >Age Group</th>
      <th >Continent</th>
      <th >Gender</th>
      <th >InceptionV3 Result</th>
      <th >VGG16 Result</th>
      <th >VGG19 Result</th>
       
       <th>Best Prediction</th>
       <th style= 'background-color: black;'></th>
       <th style= 'background-color: black;'></th>
    </tr>
  </thead>
  <tbody>
    {% for statistics in data %}
    <tr>
      <td >{{statistics.id}}</td>
      <td>{{statistics.day}}</td>
      <td>{{statistics.month}}</td>
      <td>{{statistics.year}}</td>
      <td>{{statistics.age}}</td>
      <td >{{statistics.continent}}</td>
      <td >{{statistics.gender}}</td>

      {% if statistics.result.inceptionv3_result > 0.4 %}
         <td>POSITIVE</td>
      {% else %}
          <td>NEGATIVE</td>
      {% endif %}

      {% if statistics.result.vgg16_result > 0.4 %}
         <td>POSITIVE</td>
      {% else %}
        <td>NEGATIVE</td>
      {% endif %}



      {% if statistics.result.vgg19_result > 0.4 %}

        <td>POSITIVE</td>
      {% else %}
          <td>NEGATIVE</td>
      {% endif %}

      
      
     <td>{{ statistics.result.prediction }}</td>

      <td>
        
        <a href = '{% url "covid19app:editRecord" statistics.id %}' class='btn btn-outline-primary'
        
        >Edit</a>
       
      </td>
       <td>
        
       
        <a href = "{% url 'covid19app:deleteRecord' statistics.id %}" class='btn btn-danger'
        
        >Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>


</table>

  </div>

        

<div class='container mt-3'>
    {% include 'covid19app/training.html' %}
</div>





       
    <script>

function getPointCategoryName(point, dimension) {
  var series = point.series,
    isY = dimension === 'y',
    axis = series[isY ? 'yAxis' : 'xAxis'];
  return axis.categories[point[isY ? 'y' : 'x']];
}




$(document).ready( function () {

  // $('#myTable tfoot th').each( function () {
  //       var title = $(this).text();
  //       $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
  //   } );
 

      var table = $('#myTable').DataTable({


      });



      var myChart = Highcharts.chart("container", {
        chart: {
            type: "pie"
        },
        title: {
            text: "Total Records by Continent"
        },
        series: [{
            data: chartData(table),
            name: null,
        }]
    });

        var myChart2 = Highcharts.chart("chart2", {
        chart: {
            type: "bar"
        },
        title: {
            text: "Total Covid-19 Cases"
        },
        series: [{
            showInLegend: false,
            data: pieData(table),

        }],
         tooltip: {
    formatter: function () {
      return '<b>' + this.series.name + '</b><br/>' +
        this.point.y + ' ' + this.point.name.toLowerCase();
    }
  }
    });

      
 
    // Set the data for the first series to be the map returned from the chartData function
    table.on("draw", function() {
        myChart.series[0].setData(chartData(table));
    });

    table.on("draw", function() {
        myChart2.series[0].setData(pieData(table));
    });



} );


 




 function pieData(table) {
    var counts = {};
 
    // Count the number of entries for each office
    table
        .column(10, { search: 'applied' })
        .data()
        .each(function (val) {
            if (counts[val]) {
                counts[val] += 1;
            } else {
                counts[val] = 1;
            }
        });
 
    // And map it to the format highcharts uses
    return $.map(counts, function (val, key) {
        console.table(key,val);
        return {
            name: key,
            y: val,
        };
    });
}

      function chartData(table) {
    var counts = {};
 
    // Count the number of entries for each office
    table
        .column(5, { search: 'applied' })
        .data()
        .each(function (val) {
            if (counts[val]) {
                counts[val] += 1;
            } else {
                counts[val] = 1;
            }
        });
 
    // And map it to the format highcharts uses
    return $.map(counts, function (val, key) {

        return {
            name: key,
            y: val,
        };
    });
}




 

    </script>


  {% endblock %}
  {% block custom_js %}
    
  {% endblock custom_js %}

covid19fypproj/covid19app/templates/covid19app/medical_edit.html
{% extends 'base.html' %}

{% block content %}



{% load crispy_forms_tags %}

{% include 'covid19app/_messages.html' %}


  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
   

    <button type="submit" class="btn btn-primary">Submit</button>
    {% if user.is_Medical %}
      <button type="submit" class="btn btn-outline-primary"><a href= '{% url "covid19app:medical" %}'>Back</a>
    {% else  %}
      <button type="submit" class="btn btn-outline-primary"><a href= '{% url "covid19app:it_expert" %}'>Back</a>
      {% endif %}

    </button>
  </form>
   

<img src="{{obj.image.url}}" width="300" height="300" class='d-flex align-items-center'>

  


{% endblock %}

covid19fypproj/covid19app/templates/covid19app/medical_view.html
{% extends 'base.html' %}

{% block content %}

{% include 'covid19app/_messages.html' %}


    {{data.age}}
    {{data.continent}}
    {{data.image}}



{% endblock %}

covid19fypproj/covid19app/templates/covid19app/new.html
{% extends 'base.html' %}

{% block content %}

GO TO

{% endblock %}

covid19fypproj/covid19app/templates/covid19app/result.html
{% extends 'base.html' %}

{% block content %}

{{status}}

{% if result %}

	{{result}}
{% endif %}

{% endblock %}