covid19fypproj/covid19app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .data_tables import ExpertListJson
from django.conf.urls.static import static
from django.conf import settings

app_name = 'covid19app'


urlpatterns = [
    path('', views.home, name="home"),
    path('logout', views.logout_view, name = 'logout'),
    path('login', views.login_page, name="login"),
    path('medical', views.medical, name="medical"),
    path('medical/<int:pk>', views.medical_find ,name='medical_find'),
    path('medical/new', views.addRecord, name="addRecord"),
    path('medical/<int:pk>/edit', views.edit_record, name = 'editRecord'),
    path('medical/<int:pk>/view', views.view_record , name = 'viewRecord'),
    path('medical/<int:pk>/delete', views.delete_record, name = 'deleteRecord'),
    path('medical/<int:pk>/delete_record', views.view_deleted_record , name = 'view_deleted_record'),
    path('datatable/data' ,ExpertListJson.as_view() , name = 'expert_list_json'),
    path('it_expert', views.IT_expert, name="it_expert"),
    path('help', views.help_page, name='help_page'),
    path('new', views.test_celery_route , name = 'name_page'),
    path('new/<uuid:task_id>', views.test_view_celery_result, name = 'test_view_celery_result'),
    


    


]




urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid19fypproj/covid19fypproj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('covid19app.urls')),
    path('celery-progress/', include('celery_progress.urls')),
]


handler404 = "covid19app.views.page_not_found_view"

handler500 = "covid19app.views.handler500"

covid19fypproj/covid19app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User, expertdata
from django.forms import ClearableFileInput
import os
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.core.validators import MinValueValidator
from decimal import Decimal

# Create your forms here.

class LoginForm(forms.Form):
	username = forms.CharField(
		widget = forms.TextInput(
			attrs = {
				"class": "form-control"
			}
		)
	)

	password = forms.CharField(
		widget = forms.PasswordInput(
			attrs = {
				"class": "form-control"
			}
		)
	)
	class Meta:
		model = User
		fields = ("username", "password", 'Is_medical', 'Is_expert')


def validate_file_extension(value):
   
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.png', '.jpeg', '.jpg']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Must be image with .png, .jpeg, .jpg extension')


class ImageForm(forms.ModelForm):

	files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}),validators =[validate_file_extension])

	class Meta:
		model = expertdata
		fields = ['age' , 'continent' , 'gender' , 'files']






class PublicForm(forms.ModelForm):

	# file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	# img = forms.FileField(validators =[validate_file_extension])


	def clean_image_data(self):

		return self.cleaned_data.get('image')

	class Meta:
		model = expertdata
		#Age group
		fields = ['age', 'continent', 'gender' , 'image']
		# widgets = {
  #           'file': ClearableFileInput(attrs={'multiple': True})
  #       }

class ExpertForm(forms.Form):

	class Meta:
		fields = ['dataset_directory', 'Training_data_ratio', 'batch_size', 'Models_to_use',\
		'Learning_Rate', 'Activation' , 'Regularization' , 'Regularization_Rate'
		]
	


class Covid19Form(forms.Form):

	#do not allow them to let them choose

	LOW = 16
	NORMAL = 32
	TEN_PERCENT = 10
	TWENTY_PERCENT = 20
	THIRTY_PERCENT = 30
	BATCH_SIZE_CHOICES = (
    (LOW, '16'),
    (NORMAL, '32'),
    )

    

	# only 10% 20% or 30%
	TRAINING_RATIO_CHOICES = (
		(TEN_PERCENT, '10'),
		(TWENTY_PERCENT , '20'),
		(THIRTY_PERCENT, '30'),
		)
    #vgg16 , resnet50 , inception v3

	VGG16 = 'vgg16'
	VGG19 = 'vgg19'
	INCEPTIONV3 = 'inceptionv3'


	MODELS_TO_USE_CHOICES =(
		(VGG16 , 'VGG16'),
		(VGG19 , 'VGG19'),
		(INCEPTIONV3, 'InceptionV3'),
		)

    
	SOFTMAX = 'softmax'
	SIGMOID = 'sigmoid'
	RELU = 'relu'


	ACTIVATION_METHOD_CHOICES = (
		(SOFTMAX, 'softmax'),
		(SIGMOID, 'sigmoid'),
		(RELU, 'relu'),
		)



	# directory = forms.CharField(max_length=100) # maybe remove this 
	training_ratio = forms.TypedChoiceField(choices = TRAINING_RATIO_CHOICES, label='Training Ratio',initial=10,\
		help_text = 'Refers to the percentage to be allocated for test'
		)
	batch_size = forms.TypedChoiceField(choices=BATCH_SIZE_CHOICES,label='Batch Size',initial=16,\
		help_text = 'Refers to the number of training examples utilized in one iteration. Use either 16 or 32'
		)
	models_to_use = forms.TypedChoiceField(choices = MODELS_TO_USE_CHOICES , label='Models to Use', initial='vgg16',\
		help_text =mark_safe('One of the three models to use for deep learning. <a href="https://keras.io/api/applications/vgg/">Read more here</a>.')
		)
	learning_rate = forms.DecimalField(decimal_places=5 ,validators =[MinValueValidator(Decimal('0.00001'))], max_digits = 6,label='Learning Rate',\
		help_text = mark_safe('Set to allow models to learn x-ray images at a lower rate  <a href="/help">Read more here</a>.'),
		)
	activation_method = forms.TypedChoiceField(choices = ACTIVATION_METHOD_CHOICES, label = 'Activation Method' , \
		help_text='Refers to the activation method to train the models',required=False)
	
	

covid19fypproj/covid19app/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.urls import reverse , reverse_lazy
from django.http import HttpResponse
from django.contrib.auth  import  authenticate , login , logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm #add this
from .forms import LoginForm , ImageForm , PublicForm , Covid19Form, ExpertForm
from .models import expertdata ,Result
from .filters import ImageFilter
from .permissions import medical_required , expert_required , login_excluded , logout_excluded , admin_only
from django.contrib.auth.decorators import user_passes_test 
import logging
from django.http import HttpResponse
import matplotlib.pyplot as plt
import tensorflow as tf
from PIL import Image
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import cv2
from .neural_network import hyperParameterTuning

from celery.result import AsyncResult
from keras.preprocessing import image
from .apps import Covid19AppConfig
from .task import go_to_sleep , add , get_all_data



@login_required(login_url='covid19app:login')
def test_celery_route(request):

    # sleep = go_to_sleep.delay(10)
    sleep = get_all_data.delay()
    

    return render(request, 'covid19app/new.html', {'task_id': sleep})


@login_required(login_url='covid19app:login')
def test_view_celery_result(request , task_id):

    status = AsyncResult(task_id)
    result = None

    if status.state == 'SUCCESS':
        result =status.result




    

    return render(request, 'covid19app/result.html', {'task_id': task_id, \
        'status' :status , 'result': result})




# model = tf.keras.models.load_model('static/models/vgg16_model.h5',\
#   custom_objects={'KerasLayer': hub.KerasLayer})


class_names = ['NEGATIVE','POSITIVE']

# Create your views here.


def load_and_prep_image(filename, img_shape=224):
  """
  Reads an image from filename, turns it into a tensor
  and reshapes it to (img_shape, img_shape, colour_channel).
  """
  # Decode the read file into a tensor & ensure 3 colour channels
  img = tf.io.read_file(filename)
 
  # (our model is trained on images with 3 colour channels and sometimes images have 4 colour channels)
  img = tf.image.decode_image(img, channels=3)

  # Resize the image (to the same size our model was trained on)
  img = tf.image.resize(img, size = [img_shape, img_shape])

  # Rescale the image (get all values between 0 and 1)
  img = img/255.
  return img




def home(request): # public user page
    form = PublicForm()
    pred = None
    value = None
    if request.method == 'POST':
        form = PublicForm(request.POST , request.FILES)
       
        if form.is_valid():
            print('chun was here!')
           
            new_file = form.save(commit=False)
            obj = expertdata(age = new_file.age, continent = new_file.continent , \
                    gender = new_file.gender , image = new_file.image, prediction = 25)
            obj.save() #save the instance
            messages.success(request, f'successfully uploaded files!')

            data = expertdata.objects.first()
            print(data.image)


            

            img = image.load_img(f'{data.image}',target_size=(224,224))
            img = np.asarray(img)
            img = np.expand_dims(img, axis=0)
            print(img.shape)

            vgg16 , vgg19 , inceptionv3 = 0 , 0 ,0 

            output = Covid19AppConfig.vgg16.predict(img)
            if output[0][0] > output[0][1]:
                print("POSITIVE")
                print(output[0][0])
                print(output[0][1])
                pred = 'Positive' 
                vgg16 = float(round(output[0][1], 2))

            else:
                print('NEGATIVE')
                print(output[0][0])
                print(output[0][1])
                pred = 'Negative'
                vgg16 = float(round(output[0][0], 2))

            output1 = Covid19AppConfig.vgg19.predict(img)
            if output1[0][0] > output1[0][1]:
                print("POSITIVE")
                print(output1[0][0])
                print(output1[0][1])
                pred = 'Positive' 
                vgg19 = float(round(output1[0][1], 2))
                value = vgg19

            else:
                print('NEGATIVE')
                print(output1[0][0])
                print(output1[0][1])
                pred = 'Negative'
                vgg19 = float(round(output1[0][0], 2))
                value = vgg19


            output2 = Covid19AppConfig.inceptionv3.predict(img)
            if output2[0][0] > output2[0][1]:
                print("POSITIVE")
                print(output2[0][0])
                print(output2[0][1])
                # pred = 'Positive' 
                inceptionv3 = float(round(output2[0][1], 2))

            else:
                print('NEGATIVE')
                print(output2[0][0])
                print(output2[0][1])
                # pred = 'Negative'
                inceptionv3 = float(round(output2[0][0] , 2))


            result = Result.objects.create(userid=data, inceptionv3_result=inceptionv3,\
                    vgg16_result=vgg16,\
                    vgg19_result=vgg19)
           

            data.prediction = float(value) * 100

            data.save()

            # pred = class_names[int(tf.round(prediction[0][0]))]
            # print(prediction[0][0])
                # return redirect(redirect('covid19app:home', kwargs = {'form': form}))
        # might be a problem when i refresh
        # its either i can redirect to request another page or something else
            return render(request , 'covid19app/home.html', {'form': form ,"obj" : obj , "pred" : pred })
   
    return render(request, "covid19app/home.html", {'form': form , "pred": pred })



@login_excluded('covid19app:home')
def login_page(request):


    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_Medical:
                login(request, user)
                messages.success(request, 'successfully logged in ')
                return redirect("covid19app:medical")
            elif user is not None and user.is_Expert:
                login(request, user)
                messages.success(request, 'successfully logged in ')
                return redirect("covid19app:it_expert")
            else:
                messages.error(request, 'Username or password is wrong, please try again.')
                return redirect('covid19app:login')
        else:
            messages.error(request, 'error, please check again.')
    return render(request, 'covid19app/login.html', {'form':form, 'msg':msg})

 



@logout_excluded('covid19app:home')
def logout_view(request):
    logout(request)
    messages.info(request, 'successfully logged out')
    return redirect('covid19app:home')


@medical_required
def medical(request):

    form2 = Covid19Form(request.POST or None)

    
    return render(request, 'covid19app/medical.html', {'data':expertdata.objects.all().reverse() , 'form2': form2})

def medical_find(request , pk):

    data = expertdata.objects.get(pk = pk)
    print(data)
    context = {
        'data' : data
    }

    return render(request , 'covid19app/medical_view.html', context)


# @login_required(login_url='login')


@expert_required
def IT_expert(request):

   
    form2 = Covid19Form(request.POST or None)


    data = expertdata.objects.all().reverse()

    if request.method =='POST' and form2.is_valid():
        training_ratio = form2.cleaned_data.get('training_ratio')
        learning_rate = form2.cleaned_data.get('learning_rate')
        print(training_ratio , learning_rate)

    return render(request, 'covid19app/it_expert.html' , {'form2': form2 , 'data': data})


def preprocess_image_from_infile_memory(img , shape=224):
    img = cv2.imdecode(np.frombuffer(img.read() , np.uint8), cv2.IMREAD_UNCHANGED)
    img = cv2.resize(img , (224,224))
    img = np.asarray(img).astype(np.float32)
    img = img /255.
    
    print(img.shape)
    img = np.expand_dims(img , axis=0)
    img = np.reshape(img , [1,shape,shape,3])

    return img



@medical_required
def addRecord(request):
    '''
        here we add in more images 
        change / add in 1 more file to expertdata , filefield to accept mutiple images
        insert codes for machine learning
    '''
    form = ImageForm()
    
    #[{'name': }] 


    total = []
    if request.method == 'POST':
        form = ImageForm(request.POST , request.FILES)
        files = request.FILES.getlist('files')
        count = len(files)
        if form.is_valid():
            new_file = form.save(commit=False)
            print('chun was here!')
            count = 0



            for i in request.FILES.getlist('files'):
                # print(i.name)
                # img = preprocess_image_from_infile_memory(i.name)
                # prediction = Covid19AppConfig.vgg16.predict(img)

                # prediction = prediction[0][0] * 100
               
                obj = expertdata(age = new_file.age, continent = new_file.continent , \
                        gender = new_file.gender , image = i, prediction = 25)
                count+= 1
                obj.save() #save the instance


                 
            predict = expertdata.objects.all()[:count]
            for i in predict:
                d ={}
                prediction = load_and_prep_image(f'{i.image}', 224)
                prediction3 = Covid19AppConfig.vgg16.predict(tf.expand_dims(prediction,axis=0))

                prediction1 = Covid19AppConfig.inceptionv3.predict(tf.expand_dims(prediction,axis=0))

covid19fypproj/covid19app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- dropzone js -->
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <!-- dropzone css -->
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
    
     <!-- load bootstrap libaries  -->
    {% load bootstrap5 %}

    <!-- load bootstrap css and js -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}


    <!-- sweetalert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- highcharts -->
    <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <link href="https://nightly.datatables.net/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />

    <!-- confusion matrix -->
    <script src="https://code.highcharts.com/modules/heatmap.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <!-- datatables -->
    <link rel ='stylesheet' href = '//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css'>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

    <script src='//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js'></script>

    <!-- htmlx -->
    <script src = 'https://unpkg.com/htmx.org@1.5.0'></script>



    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

     
     
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <a class="navbar-brand" href="{% url 'covid19app:home' %}">HealthCheck</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

         
           
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'covid19app:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>


        {% if user.is_authenticated %}
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Welcome,{{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!-- {% if user.is_superuser %}
              <a class="dropdown-item"  href="{% url 'admin:index' %}">Admin</a>
            {% endif %} -->
            {% if user.is_Medical %}
              <a class="dropdown-item" href="{% url 'covid19app:medical' %}">Medical Page</a>
            {% elif user.is_Expert %}
                <a class="dropdown-item" href="{% url 'covid19app:it_expert' %}">Expert Page</a>
          
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'covid19app:logout' %}">Logout</a>
          </div>
        </li>

      {% else %}

       <li class="nav-item">
             
              <a class="nav-link" href="{% url 'covid19app:login' %}">login</a>

          </li>

      {% endif %}
      <li class="nav-item">
             
              <a class="nav-link" href="{% url 'covid19app:help_page' %}"><i class="fa fa-question-circle" aria-hidden="true"></i></a>

          </li>
       

            

             

              

            

           

            


            
         

          
          <!--  <li class ="nav-item">
           <form>
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                    aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>
        </li> -->
        <!-- <li class="nav-item">
             <a class="nav-link" href = "{% url 'covid19app:help_page' %}"><i class="fa-solid fa-circle-question" data-bs-toggle="tooltip" data-bs-placement="top" title="Help"></i></a>
          </li> -->

          
        </ul>
      </div>
  </nav>

     <!--  <div class='container d-flex justify-content-center'>
        <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      </div> -->

        
      
      
         <div class='container mt-3'>

           
             {% block content %}

             {% endblock %}  



         </div>

        
   {% include 'covid19app/footer.html' %}
   <script>
      
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
})
    </script>

     <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    </script>
  </body>
</html>

covid19fypproj/covid19app/templates/help.html
{% extends 'base.html' %}

{% block content %}

<div clas="h-100 row align-items-center align-items-end">
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button text-center" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        What is the best Training Ratio?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
      Recommended ratio : 
		70% training
		30% testing 
		OR 
		80% training
		20% testing 
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        Activation Rate
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
        <p><strong>Sigmoid</strong> - simple and good for classifier </p>

		<p><strong>Softmax</strong> - produces a probability distribution for multiclass classification</p> 

		<p> <strong>Relu</strong> - simple, good for classifier and better performance</p>	

		<p><strong>Sigmoid and relu are highly recommended</strong> </p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
       Recommended Batch Size
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        Suggested batch size : 16-32
      </div>
    </div>
  </div>
   <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
       Recommend Learning rate
      </button>
    </h2>
    <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingFour">
      <div class="accordion-body">
       0.0 - 1.0
		Recommended: {0.1, .01, 10^-3, 10^-4, 10^-5}
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

covid19fypproj/covid19app/templates/lol.html
 <!-- load bootstrap libaries  -->
    {% load bootstrap5 %}

    <!-- load bootstrap css and js -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}